### ISSUE TITLE
Account login problem

### ISSUE THREAD

**Issue by 9020areeb** [Kyou-Izumi/discord-owo-selfbot#29]
I can login my account
![image]
Please fix this issue because I don't know anything about java script.

**Comment by LongAKolangle** [comment]
https://github.com/LongAKolangle/discord-owo-selfbot/discussions/15#discussioncomment-6834540

**Comment by 9020areeb** [comment]
> [#15 (reply in thread)](https://github.com/LongAKolangle/discord-owo-selfbot/discussions/15#discussioncomment-6834540)

Brother I have done the same as explained but it doesn't work for me kindly help me.
