### ISSUE TITLE
getting the same error as the fix ?? issue but even with token

### ISSUE THREAD

**Issue by TSWarrior** [Kyou-Izumi/discord-owo-selfbot#36]
The issue is same as fix?? but it is now coming with token too

**Comment by LongAKolangle** [comment]
Tried https://github.com/LongAKolangle/discord-owo-selfbot/issues/28#issuecomment-1898491555 ?

**Comment by TSWarrior** [comment]
yeah

**Comment by TSWarrior** [comment]
Thank u LongAKolangle for replying me but the issue is solved

**Comment by TSWarrior** [comment]
the issue started once again
long help me

**Comment by 0Rblx** [comment]
Also, i tried on another account. Its working on another but it doesn't work on my main.

**Comment by 0Rblx** [comment]
I tried changing token too... Keeps not working on my main.

**Comment by 0Rblx** [comment]
@LongAKolangle Please take a look when you're free
