### ISSUE TITLE
Suggestion for Huntbot captcha

### ISSUE THREAD

**Issue by uwuv3** [Kyou-Izumi/discord-owo-selfbot#41]
https://github.com/skotz/cbl-js/
You can make a captcha solver using this project. (special code is needed to remove the lines)

I'm going to remove the lines respectively

- I deleted data with alpha less than 255
* 3 missing stages *
- I filtered with Binarize
- I reversed the colors
- I separated it into blobs

I hope you can make it :)

**Comment by Kyou-Izumi** [comment]
> https://github.com/skotz/cbl-js/ You can make a captcha solver using this project. (special code is needed to remove the lines)
> 
> I'm going to remove the lines respectively
> 
> * I deleted data with alpha less than 255
> 
> * 3 missing stages *
> 
> * I filtered with Binarize
> * I reversed the colors
> * I separated it into blobs
> 
> I hope you can make it :)

Hi @uwuv3 
Thank you for your suggestions, and sorry for delayed response 
I've planned to update the code and release UI version (as promised). I'll review the PRs and other issues asap (currently away from home for personal stuff and uni preparation)

**Comment by uwuv3** [comment]
I'm sorry to bother you,
I said CBL.js because I couldn't install teserract.js,
I added command line args [Issue comes here](https://github.com/Kyou-Izumi/discord-owo-selfbot/issues/33) to turn on the bot in a single command in Pull Requests and added data to disable the auto-updater

**Comment by uwuv3** [comment]
i have send codes to you, you dont need this suggestion
